# Generated by Django 5.2.17 on 2026-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='category',
            field=models.CharField(choices=[('UI/UX', 'UI/UX'), ('Functional', 'Functional'), ('Database', 'Database'), ('Security', 'Security'), ('Performance', 'Performance')], default='Functional', max_length=20),
        ),
    ]
